apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aibutler.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aibutler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  AIBUTLER_DATA: /data
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
