apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aibutler.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aibutler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
