//go:build integration

package integration

import (
	"strings"
	"testing"
	"time"

	"github.com/LumabyteCo/aibutler/internal/agent"
	"github.com/LumabyteCo/aibutler/internal/channel"
)

// TestE2EVoiceMessageSTT sends an envelope with Type=TypeVoice and a fake audio
// attachment. The voice pipeline transcribes it to "transcribed text" via the
// StubSTTProvider. Verifies the FakeModel received text containing the transcription.
func TestE2EVoiceMessageSTT(t *testing.T) {
	p := setupPipelineWithOpts(t, pipelineOpts{
		WithVoice: true,
		Responses: []agent.Response{
			finalResponse("I heard you say something."),
		},
	})

	env := channel.Envelope{
		ID:        "voice-1",
		Channel:   "webchat",
		AccountID: "user-voice",
		Type:      channel.TypeVoice,
		Attachments: []channel.Attachment{{
			Type:     channel.TypeVoice,
			MimeType: "audio/ogg",
			Data:     []byte("fake-audio-data"),
		}},
		Timestamp: time.Now(),
	}

	if err := p.sendEnvelope(t, env); err != nil {
		t.Fatalf("sendEnvelope: %v", err)
	}

	// Verify the model was called.
	if p.Fake.CallCount() != 1 {
		t.Fatalf("model calls = %d, want 1", p.Fake.CallCount())
	}

	// Verify the transcription was passed to the model.
	calls := p.Fake.Calls()
	found := false
	for _, msg := range calls[0] {
		if strings.Contains(msg.Content, "transcribed text") {
			found = true
			break
		}
	}
	if !found {
		t.Error("model did not receive 'transcribed text' in its messages")
	}

	// Verify response was sent.
	resp := p.lastResponse(t)
	if resp != "I heard you say something." {
		t.Errorf("response = %q", resp)
	}
}

// TestE2EVoiceResponseTTS sends a voice envelope and verifies the response's
// OutgoingMessage has voice attachments (TTS audio) generated by StubTTSProvider.
func TestE2EVoiceResponseTTS(t *testing.T) {
	p := setupPipelineWithOpts(t, pipelineOpts{
		WithVoice: true,
		Responses: []agent.Response{
			finalResponse("Here is your voice response."),
		},
	})

	env := channel.Envelope{
		ID:        "voice-tts-1",
		Channel:   "webchat",
		AccountID: "user-voice-tts",
		Type:      channel.TypeVoice,
		Attachments: []channel.Attachment{{
			Type:     channel.TypeVoice,
			MimeType: "audio/ogg",
			Data:     []byte("fake-audio-data"),
		}},
		Timestamp: time.Now(),
	}

	if err := p.sendEnvelope(t, env); err != nil {
		t.Fatalf("sendEnvelope: %v", err)
	}

	// Check response has attachments (TTS audio from StubTTSProvider).
	responses := p.allResponses()
	if len(responses) != 1 {
		t.Fatalf("responses = %d, want 1", len(responses))
	}

	outMsg := responses[0]
	if len(outMsg.Attachments) == 0 {
		t.Error("expected TTS audio attachment in response, got none")
	} else {
		att := outMsg.Attachments[0]
		if att.Type != channel.TypeVoice {
			t.Errorf("attachment type = %q, want %q", att.Type, channel.TypeVoice)
		}
		if len(att.Data) == 0 {
			t.Error("TTS attachment has empty data")
		}
	}
}

// TestE2EMediaImageAttachment sends an envelope with an image attachment and
// WithMedia=true. The media pipeline processes the image and appends info to
// the text sent to the model.
func TestE2EMediaImageAttachment(t *testing.T) {
	p := setupPipelineWithOpts(t, pipelineOpts{
		WithMedia: true,
		Responses: []agent.Response{
			finalResponse("I see an image."),
		},
	})

	env := channel.Envelope{
		ID:        "img-1",
		Channel:   "webchat",
		AccountID: "user-img",
		Type:      channel.TypeText,
		Text:      "What is this?",
		Attachments: []channel.Attachment{{
			Type:     channel.TypeImage,
			MimeType: "image/jpeg",
			Data:     []byte{0xFF, 0xD8, 0xFF, 0xE0}, // JPEG magic bytes
			Filename: "photo.jpg",
		}},
		Timestamp: time.Now(),
	}

	if err := p.sendEnvelope(t, env); err != nil {
		t.Fatalf("sendEnvelope: %v", err)
	}

	if p.Fake.CallCount() != 1 {
		t.Fatalf("model calls = %d, want 1", p.Fake.CallCount())
	}

	// The model should have received text that includes the original question.
	// The media pipeline may append attachment info or the file may be unprocessable
	// (no registered processor), but the message should still go through.
	calls := p.Fake.Calls()
	foundOriginal := false
	for _, msg := range calls[0] {
		if strings.Contains(msg.Content, "What is this?") {
			foundOriginal = true
			break
		}
	}
	if !foundOriginal {
		t.Error("model did not receive original text 'What is this?'")
	}

	resp := p.lastResponse(t)
	if resp != "I see an image." {
		t.Errorf("response = %q", resp)
	}
}

// TestE2EMediaPDFAttachment sends an envelope with a minimal PDF attachment.
// Verifies the model received text with PDF content or attachment info.
func TestE2EMediaPDFAttachment(t *testing.T) {
	p := setupPipelineWithOpts(t, pipelineOpts{
		WithMedia: true,
		Responses: []agent.Response{
			finalResponse("I processed the PDF."),
		},
	})

	pdfBytes := []byte("%PDF-1.0\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Contents 4 0 R>>endobj\n4 0 obj<</Length 44>>stream\nBT /F1 12 Tf 100 700 Td (Hello World) Tj ET\nendstream\nendobj\nxref\n0 5\ntrailer<</Size 5/Root 1 0 R>>\nstartxref\n0\n%%EOF")

	env := channel.Envelope{
		ID:        "pdf-1",
		Channel:   "webchat",
		AccountID: "user-pdf",
		Type:      channel.TypeText,
		Text:      "Summarize this document.",
		Attachments: []channel.Attachment{{
			Type:     channel.TypeFile,
			MimeType: "application/pdf",
			Data:     pdfBytes,
			Filename: "document.pdf",
		}},
		Timestamp: time.Now(),
	}

	if err := p.sendEnvelope(t, env); err != nil {
		t.Fatalf("sendEnvelope: %v", err)
	}

	if p.Fake.CallCount() != 1 {
		t.Fatalf("model calls = %d, want 1", p.Fake.CallCount())
	}

	// Verify the model received the original text.
	calls := p.Fake.Calls()
	foundOriginal := false
	for _, msg := range calls[0] {
		if strings.Contains(msg.Content, "Summarize this document.") {
			foundOriginal = true
			break
		}
	}
	if !foundOriginal {
		t.Error("model did not receive original text 'Summarize this document.'")
	}

	resp := p.lastResponse(t)
	if resp != "I processed the PDF." {
		t.Errorf("response = %q", resp)
	}
}

// TestE2EMediaTextAttachment sends an envelope with a .txt file attachment.
// Verifies the media pipeline processes it and the message flows through.
func TestE2EMediaTextAttachment(t *testing.T) {
	p := setupPipelineWithOpts(t, pipelineOpts{
		WithMedia: true,
		Responses: []agent.Response{
			finalResponse("I read the text file."),
		},
	})

	txtContent := []byte("This is a plain text file with some content for testing.")

	env := channel.Envelope{
		ID:        "txt-1",
		Channel:   "webchat",
		AccountID: "user-txt",
		Type:      channel.TypeText,
		Text:      "What does this file say?",
		Attachments: []channel.Attachment{{
			Type:     channel.TypeFile,
			MimeType: "text/plain",
			Data:     txtContent,
			Filename: "notes.txt",
		}},
		Timestamp: time.Now(),
	}

	if err := p.sendEnvelope(t, env); err != nil {
		t.Fatalf("sendEnvelope: %v", err)
	}

	if p.Fake.CallCount() != 1 {
		t.Fatalf("model calls = %d, want 1", p.Fake.CallCount())
	}

	// Verify original text was passed to the model.
	calls := p.Fake.Calls()
	foundOriginal := false
	for _, msg := range calls[0] {
		if strings.Contains(msg.Content, "What does this file say?") {
			foundOriginal = true
			break
		}
	}
	if !foundOriginal {
		t.Error("model did not receive original text")
	}

	resp := p.lastResponse(t)
	if resp != "I read the text file." {
		t.Errorf("response = %q", resp)
	}
}

// TestE2EVoiceNoAttachmentData sends a voice-type envelope without any
// attachment data. The voice pipeline should fail gracefully (empty audio error)
// and the router should send an error message rather than crashing.
func TestE2EVoiceTranscribeError(t *testing.T) {
	p := setupPipelineWithOpts(t, pipelineOpts{
		WithVoice: true,
		Responses: []agent.Response{
			// The model should not be called because transcription will fail
			// and produce empty text, causing the router to send an error.
			finalResponse("Should not reach here."),
		},
	})

	env := channel.Envelope{
		ID:        "voice-empty-1",
		Channel:   "webchat",
		AccountID: "user-voice-err",
		Type:      channel.TypeVoice,
		// Empty attachments: no audio data to transcribe.
		Attachments: []channel.Attachment{},
		Timestamp:   time.Now(),
	}

	// Should not return a Go-level error; the router handles it gracefully.
	err := p.sendEnvelope(t, env)
	if err != nil {
		t.Fatalf("sendEnvelope should not return error, got: %v", err)
	}

	// The router should have sent an error message (since transcription yields
	// no text). The model should NOT have been called.
	if p.Fake.CallCount() != 0 {
		t.Errorf("model calls = %d, want 0 (transcription should have failed)", p.Fake.CallCount())
	}

	// The channel should still have received a response (the error message).
	if p.responseCount() != 1 {
		t.Fatalf("responses = %d, want 1 (error message)", p.responseCount())
	}
}
